name: Generate rules for dnsmasq
on:
  workflow_dispatch:
  schedule:
    - cron: "30 22 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "reject_list=https://raw.githubusercontent.com/maskedeken/domain-list-custom/release/category-ads-all.txt" >> $GITHUB_ENV
          echo "direct_list=https://raw.githubusercontent.com/maskedeken/domain-list-custom/release/cn.txt" >> $GITHUB_ENV
        shell: bash

      - name: Generate domestic list
        run: |
          curl -sSL ${direct_list} | grep -Ev "^(regexp|keyword):" | perl -ne '/^(full:)([-_a-zA-Z0-9]+(\.[-_a-zA-Z0-9]+)*)/ && print "ipset=/$2/whitelist\n"' >> domestic.conf
          curl -sSL ${direct_list} | grep -Ev "^(regexp|keyword|full):" | perl -ne '/^(domain:)?([-_a-zA-Z0-9]+(\.[-_a-zA-Z0-9]+)*)/ && print "ipset=/$2/whitelist\n"' >> domestic.conf

      - name: Generate adblock list
        run: |
          curl -sSL ${reject_list} | grep -Ev "^(regexp|keyword):" | perl -ne '/^(full:)([-_a-zA-Z0-9]+(\.[-_a-zA-Z0-9]+)*)/ && print "address=/$2/\n"' >> adblock.conf
          curl -sSL ${reject_list} | grep -Ev "^(regexp|keyword|full):" | perl -ne '/^(domain:)?([-_a-zA-Z0-9]+(\.[-_a-zA-Z0-9]+)*)/ && print "address=/$2/\n"' >> adblock.conf

      - name: Move files to publish directory
        run: |
          mkdir -p publish
          install -p {domestic,adblock}.conf ./publish/

      - name: Git push assets to "release" branch
        run: |
          cd publish
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "action@github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f origin release
